name: Deploy master branch

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    environment: actions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: 'Create env file'
      run: |
        echo "${{ secrets.env }}" >> .env
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Add profile credentials to ~/.aws/credentials
      env:
        AWS_PROFILE: dev
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws configure set aws_access_key_id $secrets.AWS_ACCESS_KEY_ID --profile serverlessDev
        aws configure set aws_secret_access_key $secrets.AWS_SECRET_ACCESS_KEY --profile serverlessDev
    # - name: Run tests
    #   run: npm test
    - name: Install Plugin and Deploy
      uses: serverless/github-action@v3.1
      with:
        args: -c "serverless plugin install --name serverless-iam-roles-per-function && serverless deploy --aws-profile dev"
        entrypoint: /bin/sh
    # - name: Deploy to AWS
    #   uses: serverless/github-action@v3.1
    #   with:
    #     args: deploy
      env:
        AWS_PROFILE: dev
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        
